apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
type: Opaque
data:
  AUTH_KEYCLOAK_CLIENT_ID: {{ .Values.secret.keycloak.clientId | b64enc }}
  AUTH_KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloak.clientSecret | b64enc }}

  AUTH_COOKIE_SECRET: {{ .Values.secret.auth.cookieSecret | b64enc }}

  BACKEND_AUTH_CLIENT_ID: {{ .Values.secret.backend.clientId | b64enc }}
  BACKEND_AUTH_CLIENT_SECRET: {{ .Values.secret.backend.clientSecret | b64enc }}
  BACKEND_AUTH_USERNAME: {{ .Values.secret.backend.username | b64enc }}
  BACKEND_AUTH_PASSWORD: {{ .Values.secret.backend.password | b64enc }}
