apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_CLIENT_ID: {{ .Values.secret.keycloakClientId | b64enc }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secret.keycloakClientSecret | b64enc }}
  LLM_SECRET: {{ .Values.secret.llmSecret | b64enc }}
