apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.global-static-ip-name: keycloak-ip
    networking.gke.io/managed-certificates: keycloak-cert
spec:
  ingressClassName: "gce"
  rules:
  - host: keycloak.auto-compose.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 80